name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Tests
      uses: actions/setup-node@v1
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn test
      env:
        CI: "true"